name: Build test FHIR IG

on:
  push:
    branches: [ dev-portal ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Manually trigger test FHIR IG
      run: |
        curl -X POST \
        --url "https://us-central1-fhir-org-starter-project.cloudfunctions.net/ig-commit-trigger" \
        --header "Content-type: application/json" \
        --data '{"ref": "refs/heads/main", "repository": {"full_name": "robeastwood-agency/test-fhir-ig-2"}}'
    